import { Merienda } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
const marida = Merienda({
  subsets: ["latin"],
});
export const metadata = {
  title: "Shamim",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${marida.className}`}>
      <body className="relative min-h-screen bg-slate-950 text-white overflow-x-hidden">
        <div className="pointer-events-none absolute inset-0 overflow-hidden">
          <div className="absolute top-[-10%] left-[-20%] h-[500px] w-[500px] rounded-full bg-[radial-gradient(circle_farthest-side,rgba(255,0,182,0.25),transparent)] blur-[120px]"></div>

          <div className="absolute top-[-10%] right-[-20%] h-[500px] w-[500px] rounded-full bg-[radial-gradient(circle_farthest-side,rgba(0,200,255,0.25),transparent)] blur-[120px]"></div>
        </div>

        <div className="relative z-10">
          <Navbar />
        </div>
        <main className="pt-16 md:pt-10">{children}</main>
      </body>
    </html>
  );
}
